### PR TITLE
added code-of-conduct and edited readme

### PR DESCRIPTION
**Pull request by nainardev**

### CODE REVIEW

**Comment by phoqe** [comment]
I added some more links but I am against having the Contributor Covenant Code of Conduct, or any type of Code of Conduct for that matter. I believe in just using common sense, this will just further lengthen the learning curve to get into the project.

**Comment by phoqe** [comment]
@nainardev Is that all?

**Comment by nainardev** [comment]
That's it ready to merge

**Comment by nainardev** [comment]
Maybe remove link to license in readme as it(license.md) is clearly accessible with that link

**Comment by phoqe** [comment]
@nainardev Which link?

**Comment by nainardev** [comment]
In readme.md,
headline `License` links to license.md

**Pull request merged**
